'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {Swords,Play,Settings2,BookOpen,RotateCw,Volume2,ChevronRight,Smartphone,Shield,Heart,Backpack,ScrollText,Pause,Hand,Flame,Coins,Map as MapIcon,ArrowUp,Footprints,Wind,Gem,Shirt,Sword,Plus,Check,Home as HomeIcon,Maximize,MessageCircle,Music2,VolumeX,Save,ArrowLeft,Compass,X,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {ITEMS,ZONES,XP,newState,parseSave,stats,equip,buy,spendPoint,questList,dialogue,choose,addItem,yeminler,sonMetni,type State,type ItemId,SURUM} from '@/lib/game/data';
import {Engine,SAVE,type Snapshot} from '@/lib/game/engine';
import {GameAudio} from '@/lib/game/audio';
import {makeWorld} from '@/lib/game/world';
type Panel='inventory'|'journal'|'character'|'pause'|'settings'|'help'|'credits'|'dialogue'|'shop'|'death'|'ending'|'crafting'|null;
const INITIAL=newState();INITIAL.started=false;
const ITEM_ICONS=new Set(['rusty','guard','ember','blood','bow','arrow','leather','chain','ash','copper','life','wind','potion','tonic','wood','torch','medicine','ledger','core']);
/** Esya ikonu: PixelLab ile uretilmis 32x32 PNG varsa onu, yoksa lucide simgesini cizer. */
/** Arayuz piksel ikonu. Cizgisel lucide ikonlari yalnizca uretimi iyi
 *  cikmayanlarda kaldi: ruzgar, duraklat ve konusma balonu gibi soyut
 *  simgeler 32x32 piksel artta okunmaz hale geliyordu. */
function UI({ad,size=24}:{ad:string;size?:number}){
 return <img src={`/assets/icons/ui/${ad}.png`} width={size} height={size} alt=""
  style={{imageRendering:'pixelated',display:'block'}}/>;
}
function Icon({name,size=23,item}:{name:string;size?:number;item?:string}){if(item&&ITEM_ICONS.has(item))return <img src={`/assets/icons/items/${item}.png`} width={size} height={size} alt="" style={{imageRendering:'pixelated',display:'block'}}/>;const C=({sword:Sword,flame:Flame,shirt:Shirt,shield:Shield,ring:Gem,heart:Heart,wind:Wind,potion:Heart,book:BookOpen,gem:Gem}as Record<string,typeof Sword>)[name]||Gem;return <C size={size}/>}
/** Portre: karakterin KENDI sprite'indan kafa bolgesi yakinlastirilir.
 *  Uretilen bust portreler karaktere benzemedigi ve pahali oldugu icin (25
 *  uretim/portre) kullanilmiyor; kafa bandi hepsinde x=32 merkezli, y 0..24. */
function Portrait({id=1}:{id?:number}){return <span className="portrait" style={{backgroundImage:`url('/assets/characters/${id}/D_Idle.png')`}}/>}
function Joystick({engine}:{engine:React.RefObject<Engine|null>}){const [knob,setKnob]=useState({x:0,y:0});const active=useRef<number|null>(null);const move=(e:PointerEvent<HTMLDivElement>)=>{if(active.current!==e.pointerId)return;const r=e.currentTarget.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,length=Math.hypot(dx,dy),max=r.width*.33;const x=dx/Math.max(1,length/max),y=dy/Math.max(1,length/max);setKnob({x,y});if(engine.current){engine.current.input.x=x/max;engine.current.input.y=y/max}};const end=()=>{active.current=null;setKnob({x:0,y:0});if(engine.current){engine.current.input.x=engine.current.input.y=0}};return <div className="joystick" role="group" aria-label="Hareket: parmağını istediğin yöne sürükle" onPointerDown={e=>{active.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end}><span className="stick-direction up">⌃</span><span className="stick-direction down">⌄</span><div style={{transform:`translate(${knob.x}px,${knob.y}px)`}}/><span className="control-caption">HAREKET</span></div>}
function MapView({state}:{state:State}){const w=makeWorld(state.zone);return <div className="map-layout"><svg className="dungeon-map" viewBox={`0 0 ${w.w*5} ${w.h*5}`} aria-label={`${ZONES[state.zone].name} haritası`} role="img">{w.tiles.flatMap((row,y)=>row.map((tile,x)=>tile?<rect key={`${x}-${y}`} x={x*5} y={y*5} width={5} height={5} fill="#65737f"/>:null))}{w.entities.filter(e=>['npc','portal','chest','lever','core'].includes(e.type)&&!state.opened.includes(e.id)).map(e=><circle key={e.id} cx={e.x/16*5} cy={e.y/16*5} r={e.type==='portal'?2.8:2} fill={e.type==='npc'?'#eec785':e.type==='portal'?'#86d0e0':'#aa9bc4'}/>)}<circle cx={state.x/16*5} cy={state.y/16*5} r={3.5} fill="#fff" stroke="#17232c" strokeWidth={1}/></svg><div className="map-key"><b>{ZONES[state.zone].name}</b><p>● Beyaz: sen<br/><span className="gold">● Altın: kişiler</span><br/><span className="blue">● Mavi: geçitler</span><br/><span className="purple">● Mor: nesneler</span></p><p>Sığınakta Mirna batıda, Alf doğuda, Undur güneybatıda. Sarnıca giriş güneyde.</p>{state.zone==='cistern'&&<p>İlaç ve Rauf kuzeydoğuda. Kapı kolu güneybatıda; Kül Ocağı güneydoğuda.</p>}{state.zone==='forge'&&<p>Bekçi kuzeydoğuda. Merkezdeki sandıkta Köz kılıcı var.</p>}</div></div>}
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<Engine|null>(null),audio=useRef<GameAudio|null>(null),noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const zoneTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const intro=useRef<HTMLVideoElement|null>(null);
 const [snapshot,setSnapshot]=useState<Snapshot>({state:INITIAL,near:null,attackCooldown:0,dodgeCooldown:0,tonic:0,saveStatus:'',ready:false});
 const [menu,setMenu]=useState(true),[panel,setPanel]=useState<Panel>(null),[speaker,setSpeaker]=useState('mira'),[hasSave,setHasSave]=useState(false),[confirmNew,setConfirmNew]=useState(false),[portrait,setPortrait]=useState(false),[notice,setNotice]=useState(''),[zoneFlash,setZoneFlash]=useState(''),[girisHazir,setGirisHazir]=useState(false),[yon,setYon]=useState<'yatay'|'dikey'>('yatay'),[tercihHazir,setTercihHazir]=useState(false),[music,setMusic]=useState(45),[effects,setEffects]=useState(65),[selected,setSelected]=useState<ItemId>('rusty'),[panelBack,setPanelBack]=useState<Panel>(null);
 const current=useRef({panel,menu});current.current={panel,menu};
 // Mekan adi cerceveli bildirim kutusundan ayrildi: kendi basina, buyuk ve
 // krem renkte belirip birkac saniyede soluyor.
 const flashZone=(text:string)=>{setZoneFlash(text);if(zoneTimer.current)clearTimeout(zoneTimer.current);zoneTimer.current=setTimeout(()=>setZoneFlash(''),2800)};
 const showNotice=(text:string)=>{setNotice(text);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),4800)};
 useEffect(()=>{let saved:State|null=null;try{const raw=localStorage.getItem(SAVE);saved=raw?parseSave(raw):null;if(raw&&!saved)showNotice('Eski kayıt okunamadı. Yeni bir yolculuk başlatabilirsin.');const pref=JSON.parse(localStorage.getItem('kul-yemin-audio')||'{}');if(typeof pref.music==='number'&&typeof pref.effects==='number'){setMusic(Math.min(100,Math.max(0,pref.music)));setEffects(Math.min(100,Math.max(0,pref.effects)));}if(pref.yon==='dikey'||pref.yon==='yatay')setYon(pref.yon);}catch{}setTercihHazir(true);setHasSave(!!saved);const sound=new GameAudio();audio.current=sound;const game=new Engine(canvas.current!,saved||structuredClone(INITIAL),sound,setSnapshot,event=>{if(event.type==='dialogue'){if(event.id==='crafting'){setPanel('crafting');}else{setSpeaker(event.id!);setPanel('dialogue');}}else if(event.type==='death')setPanel('death');else if(event.type==='zone')flashZone(ZONES[event.id as keyof typeof ZONES].name);else if(event.text)showNotice(event.text);});engine.current=game;
 const resize=()=>setPortrait(window.matchMedia('(orientation: portrait)').matches);resize();window.addEventListener('resize',resize);const visibility=()=>{if(document.hidden){game.setPaused(true);game.save();sound.pause(true);if(!current.current.menu)setPanel(p=>p||'pause');}else sound.pause(false);};document.addEventListener('visibilitychange',visibility);const save=()=>game.save();window.addEventListener('pagehide',save);
 return()=>{game.destroy();sound.destroy();window.removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',save);if(noticeTimer.current)clearTimeout(noticeTimer.current);if(zoneTimer.current)clearTimeout(zoneTimer.current);};},[]);
 useEffect(()=>{engine.current?.setPaused(menu||panel!==null||portrait);},[menu,panel,portrait]);
  // Ana menude muzik ve videonun kendi ruzgar sesi calar. Tarayici izinsiz
 // sesli oynatmadigi icin once denenir, olmazsa ILK dokunusta acilir.
 useEffect(()=>{if(!menu)return;
  const ac=()=>{audio.current?.start();
   const v=intro.current;if(v){v.muted=false;v.volume=.85;void v.play().catch(()=>{});}};
  ac();
  const bir=()=>{ac();window.removeEventListener('pointerdown',bir);window.removeEventListener('keydown',bir);};
  window.addEventListener('pointerdown',bir);window.addEventListener('keydown',bir);
  return()=>{window.removeEventListener('pointerdown',bir);window.removeEventListener('keydown',bir);};
 },[menu]);
 // Once video gorunsun, secenekler uzerine gelsin.
 useEffect(()=>{if(!menu){setGirisHazir(false);return;}
  const t=setTimeout(()=>setGirisHazir(true),1400);return()=>clearTimeout(t);},[menu]);
 useEffect(()=>{audio.current?.setVolumes(music/100,effects/100);
  // Yukleme bitmeden YAZMA. Ref yetmiyor: bu efekt yukleme efektinden HEMEN
  // sonra, henuz eski state ile calisiyor ve varsayilanlari kayitli tercihin
  // uzerine yaziyordu (ses seviyesi ve ekran yonu her acilista sifirlaniyordu).
  // Durum degiskeni sayesinde ilk yazma, yuklenmis degerlerin oldugu render'da olur.
  if(!tercihHazir)return;
  try{localStorage.setItem('kul-yemin-audio',JSON.stringify({music,effects,yon}));}catch{}
 },[music,effects,yon,tercihHazir]);
 useEffect(()=>{const doc=document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}};if(!doc.modelContext?.registerTool)return;const life=new AbortController();const reg=(tool:unknown)=>{try{void Promise.resolve(doc.modelContext!.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}};reg({name:'read_adventure_status',description:'Read this device’s current adventure, inventory and quests.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>{const s=engine.current!.state;return {zone:ZONES[s.zone].name,level:s.level,hp:s.hp,inventory:s.inventory,quests:questList(s),ending:s.ending};}});reg({name:'use_adventure_consumable',description:'Use an owned potion or tonic in the current active adventure, as in the inventory.',inputSchema:{type:'object',properties:{item:{type:'string',enum:['potion','tonic']}},required:['item'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const id=(input as {item?:string})?.item;if(id!=='potion'&&id!=='tonic')throw new Error('Unknown consumable.');if(current.current.menu||current.current.panel==='death')throw new Error('Resume a living adventure first.');if(!engine.current!.useItem(id))throw new Error('Item unavailable or cannot be used.');return {hp:engine.current!.state.hp,remaining:engine.current!.state.inventory[id]||0};}});return()=>life.abort();},[]);
 const s=snapshot.state,st=stats(s),quests=questList(s),activeQuest=quests.find(q=>q.active&&!q.done)||quests.find(q=>!q.done),talk=dialogue(s,speaker);
 function launch(fresh=false){audio.current?.start();const game=engine.current!;if(fresh){game.setState(newState());setSelected('rusty');}else{try{const raw=localStorage.getItem(SAVE),saved=raw?parseSave(raw):null;if(saved)game.setState(saved);}catch{}}setMenu(false);setPanel(null);setHasSave(true);setConfirmNew(false);game.start();}
 function openPanel(p:Panel){audio.current?.start();engine.current?.sound('select');setPanelBack(null);setPanel(p);}
 function closePanel(){if(panel==='death'){engine.current?.respawn();setPanel(null);return;}setPanel(panelBack);setPanelBack(null);engine.current?.emit();}
 function applyChoice(action:string){const result=choose(engine.current!.state,action);if(result.message)showNotice(result.message);engine.current!.sound(result.leveled?'level':'select');engine.current!.save();engine.current!.emit();if(result.special==='shop')setPanel('shop');else if(result.special==='ending')setPanel('ending');else if(result.special==='close')setPanel(null);}
 function selectItem(id:ItemId){const game=engine.current!;if(ITEMS[id].kind==='consumable')game.useItem(id);else if(equip(game.state,id)){game.sound('select');showNotice(`${ITEMS[id].name} kuşanıldı.`);}game.save();game.emit();}
 function mainMenu(){engine.current?.save();setMenu(true);setPanel(null);setHasSave(!!engine.current?.state.started);audio.current?.setZone('haven');}
 function fullscreen(){const d=document.documentElement;if(!document.fullscreenElement)void d.requestFullscreen?.().catch(()=>showNotice('Bu tarayıcı tam ekranı desteklemiyor. Telefonu yatay kullanabilirsin.'));else void document.exitFullscreen?.();}
 const title=panel==='dialogue'?talk.who:({inventory:'Heybe',journal:'Yolculuk defteri',character:'Gezgin',pause:'Bir nefes',settings:'Ses ve ayarlar',help:'Yola çıkmadan',credits:'Emeği geçenler',shop:'Alf’in tezgâhı',crafting:'Zanaat Masası',death:'Ateş henüz sönmedi',ending:s.ending==='seal'?'Tutulan yemin':'Yeni bir ateş'}as Record<string,string>)[panel||'']||'';
 return <main className={`game-shell ${portrait&&yon==="dikey"?"dikey":""}`} aria-label="Kül ve Yemin mobil rol yapma oyunu">
  <canvas ref={canvas} className="world" aria-label={`${ZONES[s.zone].name} oyun alanı`}/><div className="vignette"/>
  {menu?<section className="title-screen"><video ref={intro} className="intro-video" src="/assets/video/intro.mp4" poster="/assets/video/intro.jpg" autoPlay muted loop playsInline preload="auto"/><div className={`title-content ${girisHazir?"acik":""}`}><div className="chapter-label"><span/> BİR YERALTI HİKÂYESİ <span/></div><h1>KÜL <i>ve</i> YEMİN</h1><p className="title-sub">Bazı kapılar bir seçimle açılır.</p><div className="menu-buttons">{hasSave?<><button className="primary" disabled={!snapshot.ready} onClick={()=>launch()}><Play size={19} fill="currentColor"/> Yolculuğa devam et <ChevronRight size={19}/></button><button onClick={()=>setConfirmNew(true)} disabled={!snapshot.ready}><Plus size={19}/> Yeni yolculuk</button></>:<button className="primary" onClick={()=>launch(true)} disabled={!snapshot.ready}><Play size={19} fill="currentColor"/>{snapshot.ready?'Yolculuğa başla':'Dünya hazırlanıyor…'}<ChevronRight size={19}/></button>}<div className="menu-secondary"><button onClick={()=>openPanel('settings')}><Settings2 size={18}/> Ayarlar</button><button onClick={()=>openPanel('help')}><BookOpen size={18}/> Rehber</button></div></div></div><footer><button onClick={()=>openPanel('credits')}>BÖLÜM I · SON SIĞINAK</button><span><Smartphone size={15}/> YATAY · DOKUNMATİK</span></footer></section>:<>
  <header className="hud"><button className="hero-badge" onClick={()=>openPanel('character')} aria-label="Karakter ve yetenekler"><Portrait/><div><b>Gezgin <small>SV. {s.level}</small>{s.points>0&&<em>+{s.points}</em>}</b><div className="health"><span style={{width:`${s.hp/st.maxHp*100}%`}}/></div><div className="hp-row"><small>{Math.ceil(s.hp)} / {st.maxHp}</small><small className="gold"><Coins size={12}/>{s.gold}</small></div><div className="xp-bar"><span style={{width:`${s.level===5?100:(s.xp-XP[s.level-1])/(XP[s.level]-XP[s.level-1])*100}%`}}/></div></div></button><div className="zone-title">{ZONES[s.zone].name}<small>{ZONES[s.zone].danger}</small></div><nav className="hud-nav" aria-label="Oyun menüleri"><button onClick={()=>openPanel('inventory')} aria-label="Heybeyi aç"><UI ad="canta" size={27}/></button><button onClick={()=>openPanel('journal')} aria-label="Görevler ve harita"><UI ad="rulo" size={27}/></button><button onClick={()=>openPanel('pause')} aria-label="Oyunu duraklat"><Pause size={20}/></button></nav></header>
  {activeQuest&&<button className="quest-hint" onClick={()=>openPanel('journal')}><b><span className="quest-diamond">◆</span>{activeQuest.active?activeQuest.title:'İlk ışık'}</b><span>{!activeQuest.active?'Sığınaktakilerle konuş.':s.zone==='haven'?'Ayrıntılar için dokun.':activeQuest.id==='core'?'Kül kalbini bul.':'Görevini haritada takip et.'}</span></button>}
  {snapshot.tonic>0&&<div className="tonic-badge"><Flame size={15}/> +8 saldırı · {Math.ceil(snapshot.tonic)} sn</div>}
    {!panel&&<><Joystick engine={engine}/><div className="actions"><div className="utility-actions"><button className="round potion" onClick={(e)=>{(e.currentTarget as HTMLElement)?.blur();engine.current?.useItem('potion');}} aria-label={`Can iksiri iç, ${s.inventory.potion||0} adet`} disabled={!s.inventory.potion}><Icon name="flame" item="potion" size={34}/><small>{s.inventory.potion||0}</small></button><button className="round weapon" onClick={(e)=>{(e.currentTarget as HTMLElement)?.blur();engine.current?.toggleWeapon();}} aria-label="Silah değiştir"><Icon name="sword" item={s.equipment.weapon} size={32}/><small>{s.equipment.weapon==='bow'?`YAY (${s.inventory.arrow||0})`:'KILIÇ'}</small></button><button className="round dodge" onClick={(e)=>{(e.currentTarget as HTMLElement)?.blur();engine.current?.dodge();}} aria-label="Kaçın" disabled={snapshot.dodgeCooldown>0}><Wind size={25}/>{snapshot.dodgeCooldown>0&&<small>{snapshot.dodgeCooldown.toFixed(1)}</small>}</button></div><button className="round attack" aria-label="Saldır, basılı tutarak tekrarla" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);if(engine.current)engine.current.input.attack=true;}} onPointerUp={()=>{if(engine.current)engine.current.input.attack=false;}} onPointerCancel={()=>{if(engine.current)engine.current.input.attack=false;}} onLostPointerCapture={()=>{if(engine.current)engine.current.input.attack=false;}}><UI ad="saldiri" size={38}/><span>SALDIR</span></button></div>{snapshot.near&&<button className="interact available" onClick={(e)=>{(e.currentTarget as HTMLElement)?.blur();engine.current?.interact();}}>{snapshot.near.type==='npc'?<UI ad="konusma" size={22}/>:snapshot.near.type==='chest'?<UI ad="sandik" size={22}/>:snapshot.near.type==='yatak'?<UI ad="uyku" size={22}/>:<Hand size={18}/>}<span>{snapshot.near.type==='npc'?`${snapshot.near.name} ile konuş`:snapshot.near.asset?.includes('Table')?'Zanaat masasını kullan':snapshot.near.name||'Aç'}</span></button>}</>}
   <div className={`save-mark ${snapshot.saveStatus==='Kayıt yapılamadı'?'save-error':''}`}><Save size={12}/>{snapshot.saveStatus==='Kayıt yapılamadı'?'Kayıt yapılamıyor':'Cihaza otomatik kayıt'}</div>
   </>}
   {zoneFlash&&<div className="zone-flash" role="status" aria-live="polite">{zoneFlash}</div>}
  <div className="surum">v{SURUM}</div>
  {notice&&<div className="game-notice" role="status" aria-live="polite"><span>◆</span>{notice}</div>}
   <Dialog open={panel!==null} onOpenChange={open=>{if(!open&&panel!=='death')closePanel();}}><DialogContent className={`game-dialog ${panel==='dialogue'?'conversation':''} ${panel==='ending'?'ending-dialog':''}`} showCloseButton={false}><header className="panel-header"><div><span className="eyebrow">{panel==='dialogue'?talk.role:panel==='shop'?`${s.gold} altın · Muhafız malzemeleri`:panel==='crafting'?`${s.inventory.wood||0} odun · ${s.gold} altın`:panel==='ending'?'BİRİNCİ BÖLÜM TAMAMLANDI':'KÜL VE YEMİN'}</span><DialogTitle>{title}</DialogTitle></div>{panel!=='death'&&<button className="close-panel" onClick={closePanel} aria-label="Kapat"><X size={22}/></button>}</header><DialogDescription className="sr-only">{panel==='dialogue'?'Bir yanıt seç. Tercihlerin hikâyeyi değiştirir.':'Oyun bu ekran açıkken duraklatılır.'}</DialogDescription><div className="panel-body">
   {panel==='dialogue'&&<div className="dialogue-layout"><div className="speech"><Portrait id={talk.portrait}/><p>{talk.text}</p></div><div className="choices">{talk.choices.map((choice,i)=><button key={choice.action+String(i)} disabled={choice.disabled} onClick={()=>applyChoice(choice.action)}><span className="choice-number">{String(i+1).padStart(2,'0')}</span><span>{choice.label}{choice.note&&<small>{choice.note}</small>}</span><ChevronRight size={18}/></button>)}</div></div>}
   {panel==='inventory'&&<><div className="inventory-heading"><span><Coins size={18}/>{s.gold} altın</span><span>{Object.keys(s.inventory).length} eşya türü</span></div><div className="inventory-layout"><div className="item-grid">{(Object.keys(s.inventory)as ItemId[]).map(id=><button key={id} className={`item-cell ${selected===id?'selected':''} ${ITEMS[id].rarity==='Eşsiz'?'rare':''}`} onClick={()=>{setSelected(id);engine.current?.sound('select')}} aria-label={`${ITEMS[id].name}, ${s.inventory[id]} adet`}><Icon name={ITEMS[id].icon} item={id} size={32}/><span>{ITEMS[id].name}</span><small>{Object.values(s.equipment).includes(id)?'KUŞANILDI':s.inventory[id]!>1?'×'+s.inventory[id]:ITEMS[id].rarity}</small></button>)}</div><aside className="item-detail"><div className="item-emblem"><Icon name={ITEMS[selected].icon} size={64} item={selected}/></div><span className="eyebrow">{ITEMS[selected].rarity}</span><h3>{ITEMS[selected].name}</h3><p>{ITEMS[selected].description}</p>{s.inventory[selected]&&ITEMS[selected].kind!=='quest'&&<button className="primary text-button" onClick={()=>selectItem(selected)} disabled={Object.values(s.equipment).includes(selected)}>{Object.values(s.equipment).includes(selected)?'Kuşanıldı':ITEMS[selected].kind==='consumable'?'Kullan':'Kuşan'}</button>}{ITEMS[selected].kind==='quest'&&<p className="muted">İlgili kişiyle konuşarak kullanılır.</p>}</aside></div></>}
   {panel==='character'&&<><div className="character-summary"><Portrait/><div><h3>Yeminini sen yaz.</h3><p>Seviye {s.level} / 5 · {s.level===5?'En yüksek seviye':`${s.xp} / ${XP[s.level]} deneyim`}</p></div><span className="point-count">{s.points}<small>YETENEK PUANI</small></span></div><div className="stat-row"><span><Heart/> {st.maxHp}<small>CAN</small></span><span><Sword/> {st.attack}<small>SALDIRI</small></span><span><Shield/> {st.defense}<small>SAVUNMA</small></span></div><div className="skill-list">{([{key:'power',name:'Keskin el',description:'Her puan +4 saldırı.',icon:Swords},{key:'vigor',name:'Sağlam yürek',description:'Her puan +18 azami can.',icon:Heart},{key:'agility',name:'Hafif adım',description:'Kaçınma 0,25 sn daha hızlı dolar.',icon:Wind}]as const).map(skill=><div key={skill.key}><skill.icon size={24}/><span><b>{skill.name} <small>· {s.skills[skill.key]}</small></b><p>{skill.description}</p></span><button disabled={!s.points} aria-label={`${skill.name} geliştir`} onClick={()=>{if(spendPoint(engine.current!.state,skill.key)){engine.current!.sound('level');engine.current!.save();engine.current!.emit()}}}><Plus size={20}/></button></div>)}</div></>}
   {panel==='journal'&&<Tabs defaultValue="quests"><TabsList className="journal-tabs"><TabsTrigger value="quests">Görevler</TabsTrigger><TabsTrigger value="map">Harita</TabsTrigger><TabsTrigger value="history">Kararlar</TabsTrigger></TabsList><TabsContent value="quests"><div className="quest-list">{quests.map(q=><article key={q.id} className={q.done?'done':''}><span>{q.done?<Check size={20}/>:<Compass size={20}/>}</span><div><h3>{q.title}<small>{q.done?'TAMAMLANDI':q.active?'DEVAM EDİYOR':'HENÜZ ALINMADI'}</small></h3><p>{q.active||q.done?q.step:'Sığınaktaki ilgili kişiyle konuş.'}</p></div></article>)}</div></TabsContent><TabsContent value="map"><MapView state={s}/></TabsContent><TabsContent value="history"><ol className="history-list">{s.journal.slice(0,20).map((line,i)=><li key={i}>{line}</li>)}</ol></TabsContent></Tabs>}
   {panel==='shop'&&<div className="shop-list">{(['arrow','potion','tonic','chain','copper','guard','bow']as ItemId[]).map(id=><article key={id}><Icon name={ITEMS[id].icon} item={id} size={32}/><div><b>{ITEMS[id].name}{id==='arrow'?' (10 Adet)':''}</b><p>{ITEMS[id].description}</p></div><button className="text-button" disabled={s.gold<ITEMS[id].price||(ITEMS[id].kind!=='consumable'&&!!s.inventory[id])} onClick={()=>{if(buy(engine.current!.state,id)){if(id==='bow'||id==='arrow')if(s.inventory.bow)s.equipment.weapon='bow';engine.current!.sound('coin');engine.current!.save();engine.current!.emit();showNotice(ITEMS[id].name+' alındı.')}}}>{ITEMS[id].kind!=='consumable'&&s.inventory[id]?<Check size={18}/>:<><Coins size={16}/>{ITEMS[id].price}</>}</button></article>)}</div>}
   {panel==='crafting'&&<div className="shop-list">{([{id:'arrow' as ItemId,wood:1,gold:5,amount:15},{id:'bow' as ItemId,wood:5,gold:25,amount:1},{id:'potion' as ItemId,wood:3,gold:15,amount:1},{id:'tonic' as ItemId,wood:4,gold:20,amount:1},{id:'chain' as ItemId,wood:8,gold:40,amount:1}]).map(({id,wood,gold,amount})=>{const canCraft=(s.inventory.wood||0)>=wood&&s.gold>=gold;return <article key={id}><Icon name={ITEMS[id].icon} item={id} size={32}/><div><b>{ITEMS[id].name}{amount>1?` (${amount} Adet)`:''}</b><p>{ITEMS[id].description}</p><small style={{color:'#c4a377',display:'block',marginTop:'2px'}}>Gerekli: {wood} Odun · {gold} Altın</small></div><button className="text-button" disabled={!canCraft||(ITEMS[id].kind!=='consumable'&&!!s.inventory[id])} onClick={()=>{const game=engine.current!;s.inventory.wood=(s.inventory.wood||0)-wood;if(s.inventory.wood<=0)delete s.inventory.wood;s.gold-=gold;addItem(s,id,amount);if(id==='bow'||id==='arrow')if(s.inventory.bow)s.equipment.weapon='bow';game.sound('level');game.save();game.emit();showNotice(`${amount>1?amount+' adet ':''}${ITEMS[id].name} üretildi! Kuşanıldı.`);}}>{ITEMS[id].kind!=='consumable'&&s.inventory[id]?<Check size={18}/>:!canCraft?'Yetersiz Malzeme':'Üret'}</button></article>})}</div>}

  {panel==='pause'&&<div className="pause-layout"><div className="pause-status"><Portrait/><h3>{ZONES[s.zone].name}</h3><p>Seviye {s.level} · {Math.floor(s.playtime/60)} dakika</p><small><Save size={14}/>{snapshot.saveStatus||'Bu cihazda kayıtlı'}</small></div><div className="pause-buttons"><button className="primary text-button" onClick={()=>setPanel(null)}><Play size={18}/> Devam et</button><button className="text-button" onClick={()=>{setPanelBack('pause');setPanel('settings')}}><Settings2 size={18}/> Ses ve ayarlar</button><button className="text-button" onClick={()=>{setPanelBack('pause');setPanel('help')}}><BookOpen size={18}/> Kontrol rehberi</button><button className="text-button" onClick={mainMenu}><HomeIcon size={18}/> Kaydet ve menüye dön</button></div></div>}
  {panel==='settings'&&<div className="settings-layout"><div className="audio-settings"><label><span><Music2 size={20}/> Müzik <b>{music}%</b></span><Slider aria-label="Müzik seviyesi" value={[music]} onValueChange={v=>{audio.current?.start();setMusic(Array.isArray(v)?v[0]:v)}} min={0} max={100} step={5}/></label><label><span><Volume2 size={20}/> Ses efektleri <b>{effects}%</b></span><Slider aria-label="Ses efektleri seviyesi" value={[effects]} onValueChange={v=>{audio.current?.start();setEffects(Array.isArray(v)?v[0]:v)}} onValueCommitted={()=>engine.current?.sound('coin')} min={0} max={100} step={5}/></label><button className="text-button" onClick={()=>{audio.current?.start();if(music||effects){setMusic(0);setEffects(0)}else{setMusic(45);setEffects(65)}}}>{music||effects?<VolumeX size={18}/>:<Volume2 size={18}/>} {music||effects?'Tüm sesleri kapat':'Sesleri aç'}</button></div><div className="settings-notes"><div className="yon-secim"><span><Smartphone size={18}/> Ekran yönü</span><div>
  <button className={`text-button ${yon==='yatay'?'secili':''}`} onClick={()=>setYon('yatay')}>Yatay</button>
  <button className={`text-button ${yon==='dikey'?'secili':''}`} onClick={()=>setYon('dikey')}>Dikey</button>
 </div></div><button className="text-button" onClick={fullscreen}><Maximize size={18}/> Tam ekran</button><p>İlerleme bu cihazdaki tarayıcıya kaydedilir. Tarayıcı verilerini temizlemek kaydı siler.</p><p>Müzik ve efektler ilk dokunuştan sonra başlar. Başka bir uygulamaya geçtiğinde oyun duraklar.</p></div></div>}
  {panel==='help'&&<div className="help-grid"><article><Footprints/><h3>Hareket et</h3><p>Sol alandaki halkayı sürükle. Haritayı görev defterinden aç.</p></article><article><Swords/><h3>Savaş</h3><p>Saldır düğmesini basılı tut. Yakındaki düşmana otomatik yönelirsin.</p></article><article><Wind/><h3>Kaçın</h3><p>Rüzgâr düğmesiyle atıl. Kırmızı çember, düşmanın saldırmak üzere olduğunu gösterir.</p></article><article><Hand/><h3>Etkileşime geç</h3><p>Kişiye, sandığa veya kapıya yaklaş. Ortadaki düğmeye dokun.</p></article><article><Heart/><h3>Hazırlan</h3><p>Kalpten iksir iç. Heybeden ekipman kuşan; portreye dokunarak yeteneklerini geliştir.</p></article><article><ScrollText/><h3>Karar ver</h3><p>Üç görevi tamamla. Diyaloglar sırasında zaman durur; seçiminin sonucunu düşün.</p></article></div>}
  {panel==='credits'&&<div className="credits"><Flame size={38}/><h3>Kül ve Yemin</h3><p>Birinci bölüm · Son Sığınak</p><p>Piksel görseller: Craftpix — Free Top-Down Roguelike Game Kit.<br/>Başlık yazı tipi: Cinzel, SIL Open Font License.<br/>Müzik: bu oyun için hazırlanmış sığınak ve zindan temaları.</p><p className="muted">Dokunmatik, tek oyunculu RPG prototipi. Ekipman etkileri istatistiklere uygulanır; karakterin görünümü sabittir.</p></div>}
  {panel==='death'&&<div className="death-content"><Flame size={42}/><p>Mirna’nın ateşine geri dönebilirsin.<br/>Eşyaların, görevlerin ve kararların sende kalır.<br/>Altınının %10’u yolda kaybolur.</p><button className="primary text-button" onClick={()=>{engine.current!.respawn();setPanel(null)}}>Sığınakta uyan</button></div>}
  {panel==='ending'&&<div className="ending-content"><Flame size={40}/><p className="ending-prose">{sonMetni(s)}</p><div className="ending-decisions"><p><Heart size={18}/>{s.flags.medicine==='rauf'?'Rauf’a ikinci bir hayat verdin.':'Sığınağın hastalarına umut oldun.'}</p><p><Shield size={18}/>{s.flags.fugitive==='protected'?'Bir sırrı korumayı adaletten üstün tuttun.':'Rauf’un hesap vermesini seçtin.'}</p>{yeminler(s).map(y=><p key={y.kime+y.soz}><Flame size={18}/>{y.kime}: “{y.soz}” — {y.durum==='tutuldu'?'tutuldu':y.durum==='bozuldu'?'bozuldu':'ikinci bölümde sınanacak'}</p>)}</div><p className="muted">Seviye {s.level} · {quests.filter(q=>q.done).length}/{quests.length} görev · {Math.floor(s.playtime/60)} dakika</p><div className="ending-buttons"><button className="primary text-button" onClick={()=>setPanel(null)}>Sığınağı keşfetmeye devam et</button><button className="text-button" onClick={mainMenu}>Ana menü</button></div></div>}
  </div></DialogContent></Dialog>
  <AlertDialog open={confirmNew} onOpenChange={setConfirmNew}><AlertDialogContent className="new-game-dialog"><AlertDialogTitle>Yeni bir yemin?</AlertDialogTitle><AlertDialogDescription>Bu cihazdaki mevcut yolculuğun yerini yeni bir kayıt alacak.</AlertDialogDescription><div className="confirm-actions"><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction onClick={()=>launch(true)}>Yeni yolculuğa başla</AlertDialogAction></div></AlertDialogContent></AlertDialog>
  {portrait&&yon==='yatay'&&<div className="rotate-screen"><Smartphone size={48}/><h2>Telefonunu yatay çevir</h2><p>Kül ve Yemin iki elle, yatay oynanır.</p><span>Hikâyen seni bekliyor.</span><button className="text-button dikey-gec" onClick={()=>setYon('dikey')}>Dikey oynamak istiyorum</button></div>}
 </main>
}
